server:
  port: 8099

spring:
  application:
    name: PAYMENT_SERVICE

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'update'
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password